### ISSUE TITLE
Any chance for a Linux version?

### ISSUE THREAD

**Issue by sks316** [Codrax/iBroadcast-For-Windows#5]
I use Linux, but I'd like to use this iBroadcast client. My understanding is that Delphi is used for developing cross-platform apps, so I'd assume it wouldn't be a difficult port.

**Comment by Codrax** [comment]
I actually have been considering porting this to Linux with the Lazarus IDE, but currently I'm occupied with other projects. As a temporary solution, you can use Wine to run the windows version, I have tried It and while It's not pretty, It kinda works

**Comment by Codrax** [comment]
### 👀 Probably nothing...

![Screenshot from 2023-11-23 20-10-28](https://github.com/Codrax/iBroadcast-For-Windows/assets/68193064/e3efa02a-8ce6-429c-8999-3056150ae7ce)

**Comment by Codrax** [comment]
iBroadcast for Linux is now officially released. It took a while to be approved by iBroadcast, but now It's available on [GitHub](https://github.com/Codrax/iBroadcast-For-Linux) and on [my website](https://www.codrutsoft.com/apps/ibroadcast-linux/).

On the iBroadcast website, you can find your login token in Account -> Apps -> iBroadcast for Linux

Enjoy!

## Screenshot
![290873301-910eca7a-6844-4265-9e05-ceb21da1f0e3](https://github.com/Codrax/iBroadcast-For-Windows/assets/68193064/509380b3-400a-45c3-970b-f3056f60cb95)
