### ISSUE TITLE
Hangs up while Loading Artwork

### ISSUE THREAD

**Issue by keppnw** [Codrax/iBroadcast-For-Windows#6]
I just found your app, downloaded and installed the latest bits, authorized it on iBroadcast, and signed in.  All seemed to be going well until it got to the Loading Artwork phase, where it's been now for over 24 hours.  In task manager, I'm seeing User and GDI handles being used and freed, so it appears like some sort of infinite loop.  App is still responsive to mouse.  I've let it run, just to see if it'd finish, but will probably kill it before too long to see if restarting might make any difference.

For data calibration, I have around 2750 albums and about 47k tracks on iBroadcast currently.

**Comment by Codrax** [comment]
Please run the application with the `-logging` parameter from command prompt. A file will appear on your desktop. Please attach the said file here.

**Comment by keppnw** [comment]
Alright, I exited the death-looping instance, and without messing with parameters just restarted it.  This second time through, after the initial updates, it started right up!  Sorry for the bother, but it looks like I can't offer the log info for that failed initial startup. :-/

**Comment by Codrax** [comment]
The bug you described is familiar to me, I also had It happen to me ocassionally during development. I could never fix It as the next time I ran the application, the issue disappeared.

Hopefully I will be able to Identify It at some point, but currently this is out of my control.

**Comment by keppnw** [comment]
I'm open to trying to repro.  Think an uninstall/reinstall might recreate that first instance scenario?

**Comment by Codrax** [comment]
No, It happens randomly. It could be caused by a loop, a timer, a thread or an API response. A reinstall would not cause the issue to reappear. But feel free to try

**Comment by keppnw** [comment]
Yep, you're right.  It loaded right up after the reinstall.  Well, thanks for the quick responses.  If I install it on a different machine, I'll use that flag on first run just in case it chooses to repeat.
