### ISSUE TITLE
Albums that are in another language do not appear properly.

### ISSUE THREAD

**Issue by tag27** [Codrax/iBroadcast-For-Windows#8]
When the album/artist/track uses another language, such as Japanese, it is broken in the application. 

Example: 

iBroadcast website
![image](https://github.com/Codrax/iBroadcast-For-Windows/assets/68751594/90ba964c-a102-476b-9f20-1b2770b25f57)
App
![image](https://github.com/Codrax/iBroadcast-For-Windows/assets/68751594/4463f603-d054-4a62-93cd-70c9b255b3a6)

**Comment by Codrax** [comment]
I have been aware of this issue for quite a while, but rest assured I will investigate any potential fixes as soon as possible. Hopefully in the next week or so!

**Comment by Codrax** [comment]
Bug fixed in iBroadcast for Windows version 1.8.4. When opening iBroadcast, the app should prompt you to update automatically. Enjoy!
